name: test1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Pour la liste des agents
  cupertino_icons: ^1.0.2
  list_tile_more_customizable: ^3.0.0

  # Pour la lecture audio
  audioplayers: ^6.0.0

  flutter_localizations:
    sdk: flutter
  intl: any

  intl_phone_field: ^3.2.0
  flutter_locales: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.png
